# Generated by Django 2.2.2 on 2019-07-22 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='platform',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='publisher',
            new_name='platforms',
        ),
        migrations.RemoveField(
            model_name='game',
            name='artwork',
        ),
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
        migrations.RemoveField(
            model_name='game',
            name='release_date',
        ),
        migrations.RemoveField(
            model_name='game',
            name='summary',
        ),
    ]
