# Generated by Django 2.2.2 on 2019-07-22 17:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20190722_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 22, 17, 3, 41, 309859, tzinfo=utc)),
        ),
    ]
