# Generated by Django 2.2.2 on 2019-07-23 21:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_auto_20190723_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 21, 47, 45, 507306, tzinfo=utc)),
        ),
    ]
