# Generated by Django 2.2.2 on 2019-07-23 22:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_auto_20190723_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 23, 22, 4, 47, 419192, tzinfo=utc)),
        ),
    ]
