# Generated by Django 2.2.2 on 2019-07-24 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_auto_20190724_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='username',
            field=models.CharField(default='karin', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 19, 11, 57, 705371, tzinfo=utc)),
        ),
    ]
