# Generated by Django 2.2.2 on 2019-07-24 19:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0009_auto_20190724_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 19, 29, 44, 642938, tzinfo=utc)),
        ),
    ]
