# Generated by Django 2.2.2 on 2019-07-24 23:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0010_auto_20190724_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 24, 23, 31, 2, 305559, tzinfo=utc)),
        ),
    ]
