# Generated by Django 2.2.2 on 2019-07-25 20:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0016_auto_20190725_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 25, 20, 56, 9, 272037, tzinfo=utc)),
        ),
    ]
