# Generated by Django 3.1.3 on 2020-11-03 22:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0017_auto_20190725_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 3, 22, 19, 41, 381076, tzinfo=utc)),
        ),
    ]
